
openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"
servers:
  - url: "/api"
paths:
  /wiki/{data}:
    post:
      operationId: run.post_wiki
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string